window.CBT_QUIZ = {
  config: {
    pageTitle: "DGCA Module 13 Question Bank CBT",
    headerLeft: "DGCA",
    headerRight: "Module 13 Q-Bank",
    resultsTitle: "✈ QUIZ COMPLETE",
    resultsSubtitle: "DGCA Module 13 Question Bank"
  },
  questions: [
    {topic:"",q:"Flaps at landing position",opts:["decrease take off and landing speed","decrease take off speed","decrease landing speed"],ans:2,exp:""},
    {topic:"",q:"Lowering of the flaps",opts:["increases drag and lift","increases drag","increases lift"],ans:0,exp:""},
    {topic:"",q:"Pushing the left rudder pedal",opts:["yaws the aircraft left and possibly the right wing will rise","yaws the aircraft left and possibly the left wing will rise","yaws the aircraft left but has no effect on the wing"],ans:0,exp:""},
    {topic:"",q:"What preventative maintenance can be carried out in case of HIRF?",opts:["Check of aircraft structure","Bonding and insulation tests","Shielding of all sensitive equipment"],ans:2,exp:""},
    {topic:"",q:"What do ruddervators do?",opts:["Control pitch and yaw","Control pitch and roll","Control yaw and roll"],ans:0,exp:""},
    {topic:"",q:"On a helicopter what is dragging?",opts:["Movement of each blade vertically about their lateral hinges","Movement of each blade horizontally about their vertical hinge","Contact of the blade tips on the ground"],ans:1,exp:""},
    {topic:"",q:"What controls pitch and roll on a delta wing aircraft?",opts:["Elevators","Ailerons","Elevons"],ans:2,exp:""},
    {topic:"",q:"If you add an aerial, to strengthen the airframe you add",opts:["an internal doubler","external doubler","an intercostals"],ans:0,exp:""},
    {topic:"",q:"What does a trim tab do?",opts:["Eases control loading for pilot","Allows the C of G to be outside the normal limit","Provides finer control movements by the pilot Page 1 - Mod 13"],ans:0,exp:""},
    {topic:"",q:"How does a balance tab move?",opts:["In the same direction proportional to the control surface it is attached to","In the same direction a small amount","In the opposite direction proportional to the control surface it is attached to"],ans:2,exp:""},
    {topic:"",q:"Galley and cabin lighting operate on",opts:["DC bus","AC bus","GND services"],ans:2,exp:""},
    {topic:"",q:"Buffer amp on transmitter is between",opts:["modulator and power amp","local oscillator and modulator","local oscillator and demodulator"],ans:1,exp:""},
    {topic:"",q:"Aircraft is North of VOR beacon on a course of 090 RMI pointer points to",opts:["0","090","180"],ans:2,exp:""},
    {topic:"",q:"What frequency increases radar relative range",opts:["Long","Short","Radar relative range cannot be increased by frequency change"],ans:1,exp:""},
    {topic:"",q:"If radar pulse is reduced there is",opts:["increased relative range","reduced relative range","no effect"],ans:2,exp:""},
    {topic:"",q:"Adding 6 foot of cable to TX RX aerials on rad alt would give you",opts:["3 ft error","6ft error","12 foot error"],ans:0,exp:""},
    {topic:"",q:"Maximum power on a wave guide is governed by the",opts:["widest width","narrowest width","number of joints and bends"],ans:1,exp:""},
    {topic:"",q:"Which side of the pilot is the collective?",opts:["Left","Right","In-between legs"],ans:0,exp:""},
    {topic:"",q:"What effect does the ground have on a helicopter?",opts:["Increases lift","No effect","Increases thrust"],ans:0,exp:""},
    {topic:"",q:"What design factors govern RPM of a helicopter rotor?",opts:["Weight of blade","Engine and gearbox","Fineness ratio"],ans:0,exp:""},
    {topic:"",q:"Relative velocity of rotor",opts:["increases at fwd travelling blade","increases at retreating blade","is equal for all blades"],ans:0,exp:""},
    {topic:"",q:"When OAT increases what happens to an helicopter operating ceiling?",opts:["Increase","Decrease","No effect"],ans:1,exp:""},
    {topic:"",q:"How many satellites required for GNS?",opts:["8","4","6 90 o apart Page 3 - Mod 13"],ans:1,exp:""},
    {topic:"",q:"If on a lead-acid battery, several cell checks of SG read consistently low. Battery needs",opts:["topping up with distilled water","replacing","recharging"],ans:2,exp:""},
    {topic:"",q:"What happens when battery master is switched off in flight?",opts:["Battery disconnected from charge circuit","No effect","Electrical systems shut down"],ans:0,exp:""},
    {topic:"",q:"A full operational autopilot system will ensure that",opts:["the automatic pilot will automatically disengage whenever any failure is detected","the automatic pilot will automatically cause the aircraft to overshoot if any failure is detected","the aircraft will continue its automatic landing in the event of a single failure"],ans:2,exp:""},
    {topic:"",q:"What is the 'Q' code for runway heading?",opts:["QDH","QDM","QDR"],ans:1,exp:""},
    {topic:"",q:"during an automatic landing, the aircraft descent rate is sensed by",opts:["pitch rate gyros","radio altimeters","vertical accelerometers"],ans:1,exp:""},
    {topic:"",q:"the aircraft decrabbing signal, used during autoland, originates from",opts:["roll errors","localiser deviation errors","heading errors"],ans:2,exp:""},
    {topic:"",q:"An automatic throttle, engaged in the EPR mode, will control",opts:["the aircraft altitude to maintain constant engine input pressure","the engine throttles to maintain a constant acceleration rate","the engine throttles to maintain a constant engine power setting"],ans:2,exp:""},
    {topic:"",q:"Overshoot or go-around mode can be initiated",opts:["only when autopilot is engaged","after glideslope capture","at any time Page 4 - Mod 13"],ans:1,exp:""},
    {topic:"",q:"The wheel height at which the approach path has been visually assessed as satisfactory to continue the approach to a landing is known as the",opts:["decision height","intercept height","alert height"],ans:0,exp:""},
    {topic:"",q:"The International Civil Aviation Organisation weather category 3A is",opts:["operation down to and along the surface of the runway without external reference","operation down to sixty meters and RVR of 800 meters","operation down to and along the surface of the runway with RVR of 200 meters"],ans:2,exp:""},
    {topic:"",q:"Runway visual range in (RVR) is obtained by",opts:["information obtained the local Meteorological Office","three sets of instruments at the side of the runway","one set of instruments the threshold of the runway"],ans:2,exp:""},
    {topic:"",q:"A category 3B aircraft using fail operational automatic landing equipment which fail operational control and roll out guidance will have",opts:["a decision height of about 50 feet","no decision height","a decision height depending upon the RVR"],ans:1,exp:""},
    {topic:"",q:"The purpose of a yaw damper is to",opts:["assist the aerodynamic response","produce a co-ordinated turn","block the Dutch roll frequency"],ans:2,exp:""},
    {topic:"",q:"in a triplex system, the detection of a failure of one simplex system will disconnect",opts:["all channels","the failed system and carry on with an autoland","the failed system and continue with a manual approach"],ans:1,exp:""},
    {topic:"",q:"Stand off errors on localiser approach are washed out by",opts:["differentiating deviation signal","integrating deviation signal","integrating course error"],ans:2,exp:""},
    {topic:"",q:"With autothrottle selected in the SPEED MODE compatible autopilot modes are",opts:["VOR ARM and HDG HOLD","IAS HOLD and ALT ARM","V/S and ALT ARM Page 5 - Mod 13"],ans:1,exp:""},
    {topic:"",q:"Which modes are incompatible",opts:["VOR + ALTITUDE HOLD","G/S + ALTITUDE HOLD","HDG + V/S HOLD"],ans:1,exp:""},
    {topic:"",q:"To carry out an autopilot check first",opts:["switch off all power","ensure all control surfaces are unobstructed","switch on NAV receivers"],ans:1,exp:""},
    {topic:"",q:"FAIL PASSIVE means",opts:["system self monitors, failure does not affect system","system self monitors, failure does affect system","system is duplicated, failure allows aircraft to continue autoland"],ans:1,exp:""},
    {topic:"",q:"On the approach the autopilot loses the LOC signal; the aircraft would",opts:["fly a circle","increase its drift angle","fly parallel to the beam"],ans:2,exp:""},
    {topic:"",q:"The Airworthiness requirements for the autopilot / autoland system are laid down in",opts:["JAR AWO","CAIPs","BCARs"],ans:0,exp:""},
    {topic:"",q:"VOR capture can be determined by",opts:["a predetermined level of the course error signal away from the selected radial","is computed from the vectorial summation of the course error and radio deviation signals","a predetermined level of the VOR deviation signal away from the selected radial"],ans:1,exp:""},
    {topic:"",q:"Versine is generated by",opts:["torque receiver synchros","synchros resolvers","control synchro transformers"],ans:1,exp:""},
    {topic:"",q:"Automatic trim is used to",opts:["maintain level flight","prevents standing loads on the elevator","allow full authority to be regained by the aileron Page 6 - Mod 13"],ans:0,exp:""},
    {topic:"",q:"An over station sensor (OSS) is triggered by",opts:["measured radio deviation","rate of change of radio deviation","rate of change of course"],ans:1,exp:""},
    {topic:"",q:"Synchronisation circuits in autopilots ensure",opts:["that the trim indicators will read zero prior to engagement","that the autopilot control circuits are at zero demand conditions engagement","that the aircraft will always be returned to straight and level flight when the autopilot is engaged"],ans:1,exp:""},
    {topic:"",q:"In the FMS vertical navigation (V NAV) climb mode the throttles are used for",opts:["maintaining a computed EPR","controlling to a maximum thrust","correction minor speed deviations"],ans:0,exp:""},
    {topic:"",q:"The GA mode is usually initiated by",opts:["pressing a button on the control wheel","pressing a button on thrust levers","making a selection on the mode control panel"],ans:1,exp:""},
    {topic:"",q:"On selection of the Turbulence Mode",opts:["the gain is doubled to reduce oscillation","the gain remains the same but signals are phase advanced","the gain is reduced to prevent stresses to the airframe"],ans:2,exp:""},
    {topic:"",q:"To know the valid data base on the FMS",opts:["perform a BITE check","call up the relevant page on the CDU","call up the relevant current status"],ans:1,exp:""},
    {topic:"",q:"Co-ordinated autopilot turns are achieved by",opts:["yaw rate gyro signals","aileron to rudder crossfeed","aileron to elevator crossfeed"],ans:0,exp:""},
    {topic:"",q:"A yaw damper system operates on",opts:["all yaw frequencies","only mid range frequencies","low range frequencies"],ans:2,exp:""},
    {topic:"",q:"What is the impedance of VOR or HF aerial cables?",opts:["75 ohms and 25 ohms","25 ohms","50 ohms"],ans:2,exp:""},
    {topic:"",q:"In a vibrator type voltage regulator",opts:["the resistor is in series with the field","parallel with the field","in series with the voltage coil"],ans:0,exp:""},
    {topic:"",q:"Where does it state what emergency equipment and what levels of emergency equipment should be carried on an aircraft",opts:["BCAR section A4-8 or A8-4","JAR OPS","Maintenance Manual"],ans:0,exp:""},
    {topic:"",q:"If a section of the emergency floor proximity lights are inoperative",opts:["the aircraft cannot fly i.e. grounded until the defect is fixed","the aircraft can fly but the section with the problem is not used/ shut off","the aircraft is allowed to fly back to base where the defect can be fixed"],ans:2,exp:""},
    {topic:"",q:"The tail nav light. What angle of divergence should it have?",opts:["180 degrees","120 degrees","140 degrees"],ans:2,exp:""},
    {topic:"",q:"When changing the brushes on a DC generator the brushes must be bedded first, this can be done",opts:["with the generator fitted to the aircraft","the generator taken off the aircraft and bedding done on the bench","at the manufacturers only"],ans:0,exp:""},
    {topic:"",q:"What must be taken into account when measuring the SG or relative density of a lead acid battery?",opts:["The temperature","The ambient pressure","The ambient humidity Page 8 - Mod 13"],ans:0,exp:""},
    {topic:"",q:"The polythene coating on a HF antenna wire is provided",opts:["to prevent precipitation static build up","to prevent the wire from corroding","to prevent the wire from chafing"],ans:0,exp:""},
    {topic:"",q:"Weather radar domes are protected from lightning strikes by",opts:["the use of special conductive paint","bonding strips","special conducting or non-conducting grease"],ans:1,exp:""},
    {topic:"",q:"An elevator tab moves down",opts:["to counteract for the aircraft flying nose heavy","to make the nose go down","to counteract for the aircraft flying tail heavy"],ans:0,exp:""},
    {topic:"",q:"The electrolyte in a nicad battery can be checked by checking",opts:["one cell at a time until all cells are completed","only the end cell as all the others will be the same","any single cell as all the others will be the same"],ans:0,exp:""},
    {topic:"",q:"in a fly by wire system, pitch and roll control positions are known by using",opts:["LVDTs for roll control surfaces and RVDTs for pitch control surfaces","LVDTs for roll and pitch control surfaces","RVDTs for roll and pitch control surfaces"],ans:1,exp:""},
    {topic:"",q:"in a CMC aircraft, flight deck indications and warnings are managed and provided by",opts:["the central warning computer (CWC)","the electronic interface units (EIU)","the engine indicatig and crew alert system (EICAS)"],ans:2,exp:""},
    {topic:"",q:"What type of memory do CMCs have?",opts:["Volatile","Non-volatile","Hard"],ans:1,exp:""},
    {topic:"",q:"What is the purpose of the tail cone in helicopters?",opts:["To provide a balance for CofG","To hold the stabilizers and tail rotor","To provide vibration damping to the tail rotor Page 9 - Mod 13"],ans:1,exp:""},
    {topic:"",q:"An aircraft in climb maintains the same IAS. What is it's true airspeed?",opts:["Higher than its IAS","Lower than its IAS","The same as its IAS"],ans:0,exp:""},
    {topic:"",q:"The stall margin is controlled by",opts:["EPR limits","speed bug cursor","angle of attack and flap position"],ans:0,exp:""},
    {topic:"",q:"When can the FMS be engaged with the autothrottle",opts:["only with the Flight Director selected","With either the Flight Director or the Digital Control System (DFCS) engaged","only after take off"],ans:2,exp:""},
    {topic:"",q:"A full authority Digital Engine Control System (FADEC) consists of",opts:["electronic engine control unit only","electronic engine control unit and all its sensors","electronic engine control unit and throttle position transmitter"],ans:1,exp:""},
    {topic:"",q:"A FADEC system does not have the following system?",opts:["An automatic starting capability","Control of thrust reverser operation","Automatic control of engine fire extinguishers"],ans:2,exp:""},
    {topic:"",q:"Which is the correct sequence for an autoland?",opts:["Glideslope capture, altitude hold and flare","Localiser capture, glideslope capture, attitude hold and flare","Localiser capture, glideslope capture, flare and attitude hold"],ans:1,exp:""},
    {topic:"",q:"The wheel height at which the approach path has been visually assessed as satisfactory to continue the approach to a landing is know as the",opts:["decision height","intercept height","alert height"],ans:0,exp:""},
    {topic:"",q:"The ICAO weather category 3A is",opts:["operation down to and along the surface of the runway without external reference","operation down to 60 m and 800 m","operation down to and along the surface of the runway with RVR of 200m Page 10 - Mod 13"],ans:2,exp:""},
    {topic:"",q:"A category 11 facility performance ILS has an intercept height of",opts:["15 m","60 m","0 m"],ans:1,exp:""},
    {topic:"",q:"The facility performance ILS intersect height is the point",opts:["where the aeroplane receives the first glide path signal","the localiser and glide path signals cross each other","where the aeroplanes first receives both the localiser and glide path signals"],ans:0,exp:""},
    {topic:"",q:"The average risk of autoland should not contribute a rate of fatal accidents per landing greater than",opts:["1 x 10-6","1 x 10-7","1 x 10-8"],ans:1,exp:""},
    {topic:"",q:"Before an aeroplane is able to make an automatic landing the",opts:["ground radio aids must be at least CAT II","ground radio aids must be at CAT III","ILS system must be working"],ans:2,exp:""},
    {topic:"",q:"The overshoot or go around mode is initiated",opts:["automatically","by a selector on the throttle control panel","by pushing the throttles forward to maximum"],ans:2,exp:""},
    {topic:"",q:"The aeroplanes autopilot is programmed to leave the glide slope at",opts:["300 ft","the decrab phase","start of flare phase"],ans:2,exp:""},
    {topic:"",q:"Overshoot or go-around mode can be initiated",opts:["only when the autopilot is engaged","at any time after autoland has been engaged","at any time"],ans:0,exp:""},
    {topic:"",q:"The following modes may be retained when overshoot has been initiated after the selection of autoland",opts:["ILS localiser an IAS","IAS and glide slope","IAS and steering or heading Page 11 - Mod 13"],ans:2,exp:""},
    {topic:"",q:"If go-around has been initiated after autoland has been selected, the aeroplane will",opts:["increase speed","rotate nose up","increase speed and rotate nose up"],ans:2,exp:""},
    {topic:"",q:"If during autoland the LOC signal is lost at 400 ft in final approach",opts:["system degrade to CAT II","autoland is continued","go-around is initiated"],ans:2,exp:""},
    {topic:"",q:"The order of autoland approach is",opts:["LOC, GS, ATT HOLD, FLARE","GS, LOC, ATT HOLD, FLARE","LOC, GS, FLARE, ATT HOLD"],ans:0,exp:""},
    {topic:"",q:"Purpose of an autoland decrabbing manoeuvre is to",opts:["assist with localiser tracking","assist with glide slope tracking","point the aircraft down the runway at touch down"],ans:2,exp:""},
    {topic:"",q:"The effective gain of the glide path receiver",opts:["is increased as the aircraft descends","remains constant as the aircraft descends","is decreased as the aircraft descends"],ans:2,exp:""},
    {topic:"",q:"During an automatic landing, the aircraft descent rate is sensed by",opts:["pitch rate gyros","radio altimeters","vertical accelerometers"],ans:1,exp:""},
    {topic:"",q:"An autopilot with two separate power supplies is",opts:["fail passive","fail operational","fail redundant Page 12 - Mod 13"],ans:1,exp:""},
    {topic:"",q:"on touchdown, auto pilot",opts:["remains engaged ready for G/A","drives the throttles forward","disconnects after a short time"],ans:0,exp:""},
    {topic:"",q:"When will the decision height aural warning sound",opts:["at D.H.","before D.H.","after D.H."],ans:1,exp:""},
    {topic:"",q:"Automatic steering of the aircraft after touch down is affected by",opts:["the area navigation system","the runway localiser","the airfield marker beacon"],ans:1,exp:""},
    {topic:"",q:"The flare manoeuvre may be controlled by signals from",opts:["radio altimeter","the glide slope receiver","the localiser receiver"],ans:0,exp:""},
    {topic:"",q:"A triplex system looses one channel, the system is now,",opts:["fail passive","fail operational","fail redundant"],ans:1,exp:""},
    {topic:"",q:"A fail passive system in the event of failure will",opts:["produce a significant out of trim condition","produce no significant out of trim condition","ensure the aircraft can still land automatically"],ans:1,exp:""},
    {topic:"",q:"A triplex system loses one channel, the system becomes a",opts:["simplex system","duplex system","dual-dual system"],ans:1,exp:""},
    {topic:"",q:"The two parameters used for category classification are",opts:["radio height/runway visual range","localiser and glideslope","decision height and runway visual range"],ans:2,exp:""},
    {topic:"",q:"What is the controlling factor in the automatic flare mode?",opts:["Decision height","Radio altimeter","Glideslope signal Page 13 - Mod 13"],ans:1,exp:""},
    {topic:"",q:"CAT-3b allows",opts:["approach land and runway guidance with zero DH and RVR","approach land and RVR in the order of 50 meters","approach land and runway guidance with taxing visibility in the order of 50 meters"],ans:1,exp:""},
    {topic:"",q:"The definition of fail operational is the ability of a system to",opts:["disconnect and leave the aircraft in trim","continue to control after any first fault","disconnect but leave the aircraft out of trim"],ans:1,exp:""},
    {topic:"",q:"What is added to the flare computation at touchdown?",opts:["Nose down bias","Nose up bias","No signal"],ans:0,exp:""},
    {topic:"",q:"What controls are used in response to the PVD displays?",opts:["Ailerons","Throttles","Nosewheel steering or rudder pedals"],ans:2,exp:""},
    {topic:"",q:"The ground run monitor (GRM) presents",opts:["distance to go","ground speed and distance to go","take off speed and distance to go"],ans:1,exp:""},
    {topic:"",q:"for a vertical Gyro which is moved in pitch, which gimble would be moved to correct the pitch movement?",opts:["Lateral","Longitudinal","Normal"],ans:1,exp:""},
    {topic:"",q:"Versine is used in which channel?",opts:["Pitch","Roll","Yaw"],ans:0,exp:""},
    {topic:"",q:"With airspeed hold engaged whilst flying with Flight Director engaged, a down command means your speed has",opts:["increased","decreased","is the same"],ans:1,exp:""},
    {topic:"",q:"A Master Warning is issued when",opts:["overspeed and low cabin altitude occurs","cargo smoke and a low oil quantity occurs","engine fire and generator trip occurs Page 14 - Mod 13"],ans:0,exp:""},
    {topic:"",q:"The total static resistance along the length of an aircraft is",opts:["50 milliohms","1 ohms","1M - 100,000 ohms"],ans:0,exp:""},
    {topic:"",q:"In the ATA zoning where is section 100 in on an aircraft",opts:["in the undercarriage bay including the doors","at the lower section of the cabin up to the pressure bulkhead","at the rear of the fuselage behind the bulkhead"],ans:1,exp:""},
    {topic:"",q:"Sparking in a generator would be caused by",opts:["low spring tension","bedding of brushes","brushes on the Magnetic Neutral Axis"],ans:0,exp:""},
    {topic:"",q:"Which is the most important part of preventative maintenance on HIRF installations?",opts:["Visual inspections","Insulation testing","CMC fault indications"],ans:0,exp:""},
    {topic:"",q:"What should be done to a transformer secondary connections which are open circuit?",opts:["Short the terminals together","Put a set resistance across the terminals","Leave the terminals open circuit"],ans:2,exp:""},
    {topic:"",q:"If a fault is detected during an autoland approach the system will totally disconnect if it is a",opts:["Triplex system","Duplex system","Simplex system"],ans:2,exp:""},
    {topic:"",q:"A Glass Reinforced Plastic surface on an aircraft, to reduce the risk of high potential differences would be",opts:["painted in a conductive paint","painted in a non-conductive paint","bonded to the primary structure"],ans:0,exp:""},
    {topic:"",q:"The VHF aerial resistance and transmission line resistance is",opts:["50 ohms","20 ohms","20 and 50 ohms respectively Page 15 - Mod 13"],ans:0,exp:""},
    {topic:"",q:"TAS uses which inputs",opts:["Pitot and Static","Pitot and Static, Mach and Temperature","Mach and Temp"],ans:2,exp:""},
    {topic:"",q:"Other than spoilers, where are speed brakes located?",opts:["On the wing","Under the Fuselage","Either side of the Fuselage"],ans:2,exp:""},
    {topic:"",q:"With a trailing edge flap being lowered, due to rising gusts what will happen to the angle of attack?",opts:["Tend to increase","Tend to decrease","Stay the same"],ans:0,exp:""},
    {topic:"",q:"The Ground Proximity Warning Computer in mode 4 would use which inputs to issue a warning?",opts:["A low range altimeter and rate of change of low range altimeter","A low range altimeter and configuration of aircraft","A low range altimeter and GPS"],ans:1,exp:""},
    {topic:"",q:"Alert Height is when",opts:["a decision of whether to land is made","an alert of the altitude of the aircraft is made","an alert of the ground proximity is made"],ans:1,exp:""},
    {topic:"",q:"When downgrading an Autoland system what needs to be done?",opts:["Placards in the cockpit","An entry in the log book and cockpit placarding","Crew retraining"],ans:1,exp:""},
    {topic:"",q:"TCAS transmits and receives on a frequency of",opts:["1030 MHz and 1090mhz respectively","1090mhz and 1030mhz respectively","1090 MHz"],ans:0,exp:""},
    {topic:"",q:"When an aircraft is aligned for a compass swing check to be carried out it will be aligned with an error of plus or minus",opts:["1 degree","3 degree","5 degree"],ans:1,exp:""},
    {topic:"",q:"The quadrantal error in ADF is maximum at a heading of",opts:["000","045","090"],ans:1,exp:""},
    {topic:"",q:"Circulating currents is caused by an unbalanced",opts:["DC generators","AC generators","AC & DC generators"],ans:1,exp:""},
    {topic:"",q:"A device used do dump lift from an aircraft is the",opts:["spoiler","leading edge flaps","trailing edge flaps"],ans:0,exp:""},
    {topic:"",q:"Runway turn of lights have a beam width of",opts:["10 degree","110 degree","50 degree"],ans:2,exp:""},
    {topic:"",q:"Stall warning will be given at speeds",opts:["that are higher than stall speed","that are lower than stall speed","at the actual stall speed"],ans:0,exp:""},
    {topic:"",q:"when a helicopter lands how does the pilot signal to the ground staff that it is safe to approach the aircraft?",opts:["Turning on and off the NAV lights","Turning off the anti-collision lights","Flashing the landing light"],ans:1,exp:""},
    {topic:"",q:"An aircraft will capture the auto land system at",opts:["1500 ft","2500 ft","3500 ft Page 17 - Mod 13"],ans:0,exp:""},
    {topic:"",q:"FADEC system gets its power supply from",opts:["channel A and B from the same windings of a dedicated Generator","channel A and B from separate windings of a dedicated Generator","emergency Batt bus"],ans:1,exp:""},
    {topic:"",q:"Loss of an electrolyte in a battery is due to",opts:["excessive charging current","insufficient charging current","excessive charging voltage"],ans:0,exp:""},
    {topic:"",q:"An autopilot interlock circuit is to",opts:["prevent the system engagement if a fault exists","disconnect the system if a fault appears","both a & b"],ans:2,exp:""},
    {topic:"",q:"A rain fall of 5mm/hr is indicated in the WXR by a",opts:["green colour","amber","red colour"],ans:1,exp:""},
    {topic:"",q:"The international emergency frequency used in VHF Comms is",opts:["131.55","121.5","118.00"],ans:1,exp:""},
    {topic:"",q:"The electrical A/H has a movement of",opts:["85 degree in pitch and roll","360 in roll and 110 in pitch","360 in roll and 85 in pitch"],ans:2,exp:""},
    {topic:"",q:"When working on a hydraulic operated flight control it is sensible to",opts:["remove/disconnect hydraulic power","remove/disconnect electrical power","pull the appropriate CB"],ans:0,exp:""},
    {topic:"",q:"Emergency electronic equipment requirement will be found in",opts:["CAAIPs","Maintenance Manual","JAR OPS Page 18 - Mod 13"],ans:2,exp:""},
    {topic:"",q:"When an aircraft is at a height of 9500ft and the QNH is 500 ft what is the distance that VHF Com cover?",opts:["100 nm","120 nm","140 nm"],ans:1,exp:""},
    {topic:"",q:"When the VOR ref and Vari phase are in phase quadrature, the aircraft is at the",opts:["180 degree radial","090 degree radial","275 degree radial"],ans:1,exp:""},
    {topic:"",q:"A unit with two springs and a mass pick off is",opts:["an accelerometer","a gyroscope","a tachogenerator"],ans:0,exp:""},
    {topic:"",q:"The units of vibration are measured in",opts:["phons","decibels","relative amplitude"],ans:2,exp:""},
    {topic:"",q:"Magnetic variation is the difference in angle between",opts:["true north and magnetic north","magnetic heading and aircraft heading","the compass north and magnetic north"],ans:0,exp:""},
    {topic:"",q:"GPWS mode 1 is excessive",opts:["terrain closure","rate of ascent","rate of descent"],ans:2,exp:""},
    {topic:"",q:"The applied pressure to an ASI varies with the",opts:["square of the speed","square root of the speed","cube root of the speed Page 19 - Mod 13"],ans:0,exp:""},
    {topic:"",q:"Temperature compensation is required on an altimeter because of",opts:["capsule elasticity","capsule shape","non linear pressure/height relationship"],ans:0,exp:""},
    {topic:"",q:"The loss of the vertical gyro signal to the flight director system would cause",opts:["aircraft to underbank","aircraft to overbank","aircraft to remain in level flight"],ans:1,exp:""},
    {topic:"",q:"The doppler VOR beacon reference signal",opts:["amplitude modulates the carrier frequency","amplitude modulates the sub carrier frequency","frequency modulates the sub carrier frequency"],ans:0,exp:""},
    {topic:"",q:"During flare mode autothrottle will",opts:["retard throttles to idle","disconnect autothrottle","select reverse thrust"],ans:0,exp:""},
    {topic:"",q:"A CSD is monitored for",opts:["low temp and high oil pressure","high temp and low oil pressure"],ans:1,exp:""},
    {topic:"",q:"As the rotor head is tilted to travel forward what happens to the reward travelling blades pitch angle?",opts:["Increases","Decreases","No change"],ans:0,exp:""},
    {topic:"",q:"What is the power supply to cabin flow tubes?",opts:["115v ac","200v ac","High voltage stepped up"],ans:2,exp:""},
    {topic:"",q:"When all three leads of a bonding tester are connected together the output reading is",opts:["zero","full scale deflection","centre scale Page 20 - Mod 13"],ans:0,exp:""},
    {topic:"",q:"in a capacitive fuel gauging system an increase in fuel level would",opts:["increase capacitive reactance","increase capacitance","decrease capacitance"],ans:1,exp:""},
    {topic:"",q:"A vertical structural member forming part or full walls are",opts:["bulkheads","longerons","frame"],ans:0,exp:""},
    {topic:"",q:"Low electrolyte in a nicad battery is caused by",opts:["excessive electrical loading","high charge current","low charge current"],ans:0,exp:""},
    {topic:"",q:"To ensure the compass is serviceable before installation you would carry out",opts:["damping and periodicity checks","damping and pivot friction check","damping and alignment checks"],ans:1,exp:""},
    {topic:"",q:"Suppressor line is required for",opts:["ATC and DME only","TCAs only","all L band equipments including TCAS"],ans:2,exp:""},
    {topic:"",q:"A manual trim wheel, when fully moved in the direction of tail",opts:["the authority of elevators not effected","the up movement authority is effected","the down movement authority is effected"],ans:1,exp:""},
    {topic:"",q:"If on an ILS approach, LOC signal is lost",opts:["aircraft continues to descent with an accumulating drift","aircraft descends in a parallel path to runway","aircraft moves in a circle"],ans:1,exp:""},
    {topic:"",q:"IDG output voltage",opts:["does not require voltage regulation as RPM is constant.","voltage is regulated by GCU","voltage is regulated by IDG"],ans:1,exp:""},
    {topic:"",q:"The over-station sensor is activated by",opts:["radio deviation signal","rate of radio deviation signal","deviation and course error"],ans:1,exp:""},
    {topic:"",q:"When moving the control column",opts:["sensors located under the control column produces a signal","sensor located along the control run produces a signal","sensor in the AFCS computer produces a signal","the elevator causes tail down movement i.e. increases tail plane down force force Page 22 - Mod 13"],ans:0,exp:""},
    {topic:"",q:"Equivalent airspeed is",opts:["indicated airspeed corrected for IE and PE","rectified airspeed corrected for compressibility","calibrated airspeed corrected for compressibility"],ans:2,exp:""},
    {topic:"",q:"in an Autoland, autothrottle is disengaged",opts:["after reverse thrust is applied","after affixed period of the time after landing","manually after landing"],ans:0,exp:""},
    {topic:"",q:"What is the maximum limit of the artificial horizon?",opts:["85 degrees in pitch and 360 degrees in roll","360 degrees in pitch and roll","85 degrees pitch and 110 degrees in roll"],ans:0,exp:""},
    {topic:"",q:"Acceleration error produces",opts:["a false indication of left bank","a false indication of right bank","a false indication of climb"],ans:1,exp:""},
    {topic:"",q:"Zone 500 indicates as per ATA 100",opts:["Door","Left wing","Right wing"],ans:1,exp:""},
    {topic:"",q:"Shock stall",opts:["is a flap down stall","occurs at high speeds","occurs at low speeds"],ans:1,exp:""},
    {topic:"",q:"Drooping of helicopter blades is compensated by",opts:["flapping","dragging","centrifugal force"],ans:2,exp:""},
    {topic:"",q:"During a turn",opts:["left rudder to be used","right rudder to be used","rudder to be maintained in centre position Page 23 - Mod 13"],ans:2,exp:""},
    {topic:"",q:"Align light flashes during alignment",opts:["A fault has occurred and system needs to be turned off","It is attracting operators attention","It is indicating progress of alignment"],ans:0,exp:""},
    {topic:"",q:"During decent with power on in a helicopter",opts:["lift, drag and thrust are acting on the helicopter","lift, drag, thrust and weight are acting on the helicopter","lift, weight and thrust are acting on the helicopter"],ans:1,exp:""},
    {topic:"",q:"to transmit position feedback for actuators of roll and pitch control surfaces, in a fly by wire system",opts:["LVDT is used hence ensuring interchangeability","LVDT and RVDT are used for pitch and roll","Synchros are used"],ans:0,exp:""},
    {topic:"",q:"The compensator in a fuel tank measures",opts:["specific gravity of fuel","K value of fuel","fuel quantity"],ans:1,exp:""},
    {topic:"",q:"What is the error signal used for in a fixed angle approach in LOC coupling?entrifugal force",opts:["Heading and Deviation","Course error and Deviation","Heading,Course error and Deviation"],ans:1,exp:""},
    {topic:"",q:"in modern aircraft, power distribution of Generators are controlled by",opts:["BPCU","PCDU (power control distribution unit)","SPCU"],ans:0,exp:""},
    {topic:"",q:"As you approach supersonic",opts:["total drag is increased","lift is reduced","thrust is reduced"],ans:0,exp:""},
    {topic:"",q:"Range resolution is obtained by",opts:["High PRF","Shorter pulse width","Shorter beam width"],ans:1,exp:""},
    {topic:"",q:"in weather radar, short range targets are missed by",opts:["Larger pulse width","Larger beam width","Larger frequency Page 24 - Mod 13"],ans:0,exp:""},
    {topic:"",q:"When the trailing edge flap is",opts:["The CP moves forward and the pitching moment changes to nose up","The CP moves forward but the CG does not change","CP move rearward"],ans:2,exp:""},
    {topic:"",q:"During take off if an input to auto throttle is fails",opts:["Auto throttle disengages","Throttle hold is annunciated","Fail light illuminates"],ans:1,exp:""},
    {topic:"",q:"Flight director command bars indicate",opts:["Direction in which aircraft is to be manoeuvred","Direction in which aircraft is flying","Direction in which the beacon is"],ans:0,exp:""},
    {topic:"",q:"Mode S has",opts:["12 address bits","24 address bits","36 address bits"],ans:1,exp:""},
    {topic:"",q:"If an aircraft is on east of VOR beacon, the reference and variable phases are",opts:["In phase","Opposite phase","Phase quadrature"],ans:2,exp:""},
    {topic:"",q:"In a radio altimeter system if you decide to increase the TX cable and RX cable each by 3 inch the total correction factor is",opts:["3 inch","6 inch","9 inch"],ans:2,exp:""},
    {topic:"",q:"If you momentarily short the two spikes of bonding tester",opts:["tester reads zero","tester reads full scale","tester would be zero centred"],ans:1,exp:""},
    {topic:"",q:"for bonding, the two ends of a rubber pipe are joined by",opts:["a thick metallic bonding strip","a corrugated bonding jumper","a wire attached by terminal legs at both ends Page 25 - Mod 13"],ans:1,exp:""},
    {topic:"",q:"What is the minimum resistance between all isolated electrostatic conducting parts which may be subjected to appreciable charge and main earth system",opts:["0.5 ohm","1 ohm","0.5 Megohm or 100,000 ohm/sq.ft. surface area which ever is less"],ans:2,exp:""},
    {topic:"",q:"Mach trim in some aircraft assists",opts:["longitudinal stability","lateral stability","vertical stability"],ans:0,exp:""},
    {topic:"",q:"In case the airplane is wired for dual installation of the Central Maintenance Computers and only one computer is to be installed",opts:["it must be installed on LH side","it must be installed on RH side","it may be installed either on LH or RH side"],ans:0,exp:""},
    {topic:"",q:"If the static line is disconnected in the cabin, the Mach meter reading would be",opts:["higher mach number","lower mach number","not effected"],ans:1,exp:""},
    {topic:"",q:"in a dual FMC installation, if one FMC is defective",opts:["one CDU blanks","both CDU blanks","not be affected as automatic transfer takes place"],ans:2,exp:""},
    {topic:"",q:"While carrying out a leak check of the altimeter, if the static is leaking, the VSI would",opts:["indicate climb","indicate decent","not be affected"],ans:1,exp:""},
    {topic:"",q:"What is the authority of series actuator on an helicopters autopilot?",opts:["10%","50%","100%"],ans:0,exp:""},
    {topic:"",q:"in helicopter autopilots, while operating the actuator, the movement of the cockpit control is prevented by",opts:["synchros attached to the control","a compressed spring attached to the cockpit control","a lock on the cockpit control"],ans:1,exp:""},
    {topic:"",q:"Helicopter blades are",opts:["highly cambered","reverse cambered","Symmetrical"],ans:2,exp:""},
    {topic:"",q:"The cyclic stick in an helicopter is",opts:["to the left","to the right","in the centre Page 27 - Mod 13"],ans:2,exp:""},
    {topic:"",q:"An autopilot computer",opts:["is more sensitive to ILS than to VOR","is more sensitive to VOR than to ILS","is the same sensitivity for VOR and ILS --------240. What type of flap is this?","Split flap"],ans:3,exp:""},
    {topic:"",q:"Purpose of the bellcrank is to",opts:["transmit motion","reverse direction and transmit motion","adjust friction"],ans:1,exp:""},
    {topic:"",q:"Index error is",opts:["coefficient B","Coefficient P","misalignment of compass lubber line"],ans:2,exp:""},
    {topic:"",q:"Helicopter derives its lift from",opts:["the blade of the helicopter creates a low pressure above it","rotor acts as a airscrew","air is pushed downward"],ans:0,exp:""},
    {topic:"",q:"A two bladed helicopter rotor on a central gimbal is called",opts:["rigid rotor","semi rigid rotor","fully articulated rotor Page 28 - Mod 13"],ans:1,exp:""},
    {topic:"",q:"If the 'Q' feel in a powered control system fails",opts:["the failed system stops and it remains in this position","the pilot feels air loads higher than normal","the pilot feels air loads lower than normal"],ans:2,exp:""},
    {topic:"",q:"When the bank angle limit is applied to the autopilot, it means",opts:["the max aileron angle that can be commanded","the max roll angle that can be demanded by the autopilot","maximum rudder deflection"],ans:1,exp:""},
    {topic:"",q:"Servo tabs",opts:["enable the pilot to bring the control surface back to neutral","move in such a way as to help move the control surface","provide artificial feel"],ans:1,exp:""},
    {topic:"",q:"Spring Tabs",opts:["enable the pilot to bring the control surface back to neutral","move in such a way as to help move the control surface","provide artificial feel"],ans:1,exp:""},
    {topic:"",q:"Omega ground stations",opts:["transmit pulses of CW","carrier modulated by three audio tones","series of CW"],ans:0,exp:""},
    {topic:"",q:"When secondary stops are utilized in control surfaces, they come in contact",opts:["before the primary stops","after the primary stops","at the same time as the primary stops"],ans:1,exp:""},
    {topic:"",q:"EICAS indicates",opts:["engine performance and aircraft system malfunctions","engine performance only","engine performance and aircraft status"],ans:0,exp:""},
    {topic:"",q:"Helicopter cyclic stick is turned to the right",opts:["rotating aerofoil tilts to the right","pitch operating arms lengthen in one direction and shorten in another","rotating aerofoil tilts to the right"],ans:0,exp:""},
    {topic:"",q:"Magnetic heading errors will be",opts:["positive if easterly","negative if easterly","negative if northerly"],ans:0,exp:""},
    {topic:"",q:"What will happen with a flux valve in a turn?",opts:["It moves once the aircraft is established on a new heading","It move as the aircraft moves","It stays fixed on magnetic north"],ans:1,exp:""},
    {topic:"",q:"When will a mode C interrogation be ignored?",opts:["When the P2 pulse is higher amplitude to P1","When the P2 pulse is antiphase to P1","If P2 is before P1"],ans:0,exp:""},
    {topic:"",q:"An aircraft with autoland is fitted with a CMC",opts:["records all faults in volatile memory","records all faults in non-volatile memory"],ans:1,exp:""},
    {topic:"",q:"A helicopter autopilot uses",opts:["radio altitude for height hold and barometric altitude for altitude hold","barometric altitude for height hold and radio altitude for altitude hold","barometric altitude for both height and altitude hold"],ans:0,exp:""},
    {topic:"",q:"On an ILS approach what will cause the aircraft to fly onto the beam?",opts:["Radio deviation","Glideslope deviation","Course deviation Page 30 - Mod 13"],ans:2,exp:""},
    {topic:"",q:"Which of the following modes does a autopilot go through in correct sequence?",opts:["Flare, attitude, rollout","Attitude, flare, rollout","Rollout, attitude, flare"],ans:1,exp:""},
    {topic:"",q:"If a helicopter rotor disc is rotating anticlockwise, viewed from above where would a pitch input be fed into the disc to move the helicopter backwards, 90 degrees to what?",opts:["In front of the lateral axis","Right of the longitudinal axis","Left of the longitudinal axis"],ans:1,exp:""},
    {topic:"",q:"A spring balance control system you",opts:["can move the control surface on the ground","can move the control surface only by moving the tab","cannot move the control surface on the ground"],ans:0,exp:""},
    {topic:"",q:"Why is a wire HF antenna covered in polythene?",opts:["To prevent corrosion","To prevent precipitation static","To provide lightning protection"],ans:1,exp:""},
    {topic:"",q:"If a VOR RMI indicates 000 degrees and the course selected is 000 degrees what will the TO/FROM indicator indicate?",opts:["TO","FROM","Neither"],ans:2,exp:""},
    {topic:"",q:"What does the Radar contour button do?",opts:["Alter the beam shape","Alter the transmitter power","Alter the video amplifier"],ans:0,exp:""},
    {topic:"",q:"on a helicopter, what is vortex ring state?",opts:["Tip vortex interference at high forward speed","Ground vortex interference when hovering close to the ground","Tip vortex build-up during hover"],ans:2,exp:""},
    {topic:"",q:"What controls are used in response to PVD display?",opts:["Nose wheel steering or rudder pedals","Control wheel","PVD control unit"],ans:0,exp:""},
    {topic:"",q:"DME transponder transmits on receipt",opts:["of any interrogation","of pilot input command request","of a pair of pulses separated by 12 microseconds"],ans:2,exp:""},
    {topic:"",q:"The best design of a MRB is where the C of P",opts:["does not move","moves freely along the length of the blade","is insignificant"],ans:0,exp:""},
    {topic:"",q:"The RAD alt electrical length for an helicopter is",opts:["16ft","12ft","28ft Page 32 - Mod 13"],ans:2,exp:""},
    {topic:"",q:"Mode S transponders transmits a binary code of",opts:["12bits","64bits","24bits"],ans:2,exp:""},
    {topic:"",q:"The rotor cone is formed by",opts:["blade alignment","centrifugal force and lift","centrifugal force only"],ans:1,exp:""},
    {topic:"",q:"Tracking is carried out to_____________the MRB tip path",opts:["balance","restore","align"],ans:2,exp:""},
    {topic:"",q:"Artificial feel is gained by using a",opts:["hydraulic damper","spring bias unit","'feel' generator"],ans:1,exp:""},
    {topic:"",q:"The ground run monitor presents information",opts:["of distance to go and ground speed","duration of ground run","angle of crosstrack on ground"],ans:0,exp:""},
    {topic:"",q:"A mode C transponder",opts:["can be used for TCAS","cannot be used for TCAS","can be used for TCAS on ILS approach only"],ans:1,exp:""},
    {topic:"",q:"The audio select panel allows the crew to",opts:["transmit on one channel, listen on one","transmit on one channel, listen on multiple others","receive on one channel, transmit on multiple others"],ans:0,exp:""},
    {topic:"",q:"The crew select DH on",opts:["the altimeter","the DH annunciator panel","the rad alt display"],ans:2,exp:""},
    {topic:"",q:"When substituting the radio altimeter antenna cables, you should consider",opts:["power requirements","the speed of propagation of rad alt signal","the diameter of cables Page 33 - Mod 13"],ans:1,exp:""},
    {topic:"",q:"GPS has",opts:["24 satellites, 6 orbits of 4","24 satellites, 4 orbits of 6","27 satellites, 3 orbits of 9"],ans:0,exp:""},
    {topic:"",q:"Audio select panel voice switch",opts:["allows voice ident of DME","cuts \"beeps\" from DME signal","disables DME voice ident"],ans:1,exp:""},
    {topic:"",q:"GPS frequency is",opts:["1575 GHz","1575 MHz","1525 MHz"],ans:1,exp:""},
    {topic:"",q:"Radio switches are normally",opts:["sprung on R/T, latched on I/C","latched on R/T, sprung on I/C","latched on R/T, latched on I/C"],ans:0,exp:""},
    {topic:"",q:"on GPWS, with aircraft below 1700ft",opts:["systems is disabled","no traffic will be shown","all traffic produces aural alert"],ans:0,exp:""},
    {topic:"",q:"Mode S pulses. Which are used?",opts:["F1,F2,F4,F5","s1,p1,p3,p4","s1,s2,p1,p2"],ans:1,exp:""},
    {topic:"",q:"in a superhet receiver, the advantage of an RF amplifier is",opts:["it amplifies output stages","it improves signal to noise ratio","it couples noise factors"],ans:1,exp:""},
    {topic:"",q:"Fluorescent tubes for the cabin lighting are powered from",opts:["115 volts from ac bus","200 volts from ac bus","high voltage produced by transformer ballast units"],ans:2,exp:""},
    {topic:"",q:"The advancing blade of a helicopter is the one moving",opts:["one moving in direction of relative air flow","highest blade","one moving forward into relative airflow Page 34 - Mod 13","voltage and current coil"],ans:3,exp:""},
    {topic:"",q:"in air speed hold mode, a down displacement of the flight director pitch command bar signifies",opts:["speed increase","speed decrease","height decrease"],ans:1,exp:""},
    {topic:"",q:"Back beam is captured",opts:["by manually selecting the back beam mode","this automatically trips the L NAV mode","by manually selecting the L NAV mode"],ans:0,exp:""},
    {topic:"",q:"With an insulation tester",opts:["the long lead is attached to the aircraft air frame and short lead to item","the short lead to the aircraft airframe and long lead to the item","it does not matter which lead goes where"],ans:2,exp:""},
    {topic:"",q:"DME reply pulses are 63MHZ",opts:["higher","lower","higher or lower"],ans:2,exp:""},
    {topic:"",q:"What is VHF comm range at 9000 feet?",opts:["110 nm","120 nm","130 nm"],ans:1,exp:""},
    {topic:"",q:"Medium vibration of 4 to 6 times per revolution is experienced on a helicopter. The primary control method is",opts:["inspect loose fixtures and fittings","design of engine and gearbox supports","inspect main rotor head and main drive shaft"],ans:1,exp:""},
    {topic:"",q:"Krueger flaps make up part of the",opts:["wing upper surface leading edge","wing lower surface trailing edge","wing lower surface leading edge"],ans:2,exp:""},
    {topic:"",q:"Electronic stab trim switches are found on the",opts:["control column","flight control panel","behind thrust levers"],ans:0,exp:""},
    {topic:"",q:"Emergency electronic equipment for the cabin is referred to in",opts:["BCARs","JAR OPS subpart M","maintenance manual"],ans:1,exp:""},
    {topic:"",q:"Carbon microphones require",opts:["DC supply","AC supply","no supply"],ans:0,exp:""},
    {topic:"",q:"A CVR is found to be unserviceable",opts:["flight can continue with serviceable FDR provided they are not combined","flights must not continue after four days","flights must not continue after 72 hours"],ans:2,exp:""},
    {topic:"",q:"The maximum azimuth coverage by a MLS facility is",opts:["+/- 35 degrees","+/-40 degrees","+/-60 degrees Page 36 - Mod 13"],ans:1,exp:""},
    {topic:"",q:"Fibre glass parts are protected from lightning strikes and dangerous voltages by",opts:["non conductive paint","conductive paint","earth primary conductors"],ans:2,exp:""},
    {topic:"",q:"The pseudo-random code used by all civilian GPS users is",opts:["the y code","the p code","the c/a code"],ans:2,exp:""},
    {topic:"",q:"On localiser approach the radio deviation signal is lost",opts:["the aircraft flies in a circle","aircraft flies off centre line on pre-set heading","aircraft flies heading with increasing drift angle"],ans:1,exp:""},
    {topic:"",q:"'Q' feel for the stabiliser requires",opts:["pitot only","static only","pitot and static"],ans:2,exp:""},
    {topic:"",q:"When the aircraft nose yaws to the left, the yaw damper will apply corrective rudder to",opts:["the right","the left","the left with some aileron assistance"],ans:0,exp:""},
    {topic:"",q:"A yaw damper will apply rudder proportional to",opts:["amount of aircraft disturbance","attitude of aircraft","rate of yaw Page 37 - Mod 13"],ans:2,exp:""},
    {topic:"",q:"In a turn, wing spoilers may be deployed",opts:["to act as an airbrake, interacting with the ailerons","in unison with both the up going and down going ailerons","to assist the up going aileron"],ans:2,exp:""},
    {topic:"",q:"Glideslope deviation signals are",opts:["DC polarity sensitive","AC phase sensitive","DC positive going only"],ans:0,exp:""},
    {topic:"",q:"A triplex system loses one channel",opts:["pilot can continue with autoland","pilot can use auto approach","pilot must make a full manual approach and land"],ans:0,exp:""},
    {topic:"",q:"A series actuator in a helicopter autopilot system has",opts:["full authority","50% authority","10% authority"],ans:2,exp:""},
    {topic:"",q:"Stall warning will be given",opts:["before stall","after stall","at stall"],ans:0,exp:""},
    {topic:"",q:"With on-board maintenance (OBM) systems, the purpose of central maintenance function (CMF) is to",opts:["log relevant maintenance data","transmits to the CMC","provides details of defect action"],ans:0,exp:""},
    {topic:"",q:"How are spoilers normally operated?",opts:["Hydraulic actuator","Air pistons","Electrical motors"],ans:0,exp:""},
    {topic:"",q:"The purpose of a force trim release system in an helicopter is to permit the",opts:["pilot to move the cyclic stick to obtain desired new attitude without having to maintain the opposing forces of the artificial feel system forces","pilot to move the collective to obtain a power change","appropriate cyclic actuator to be over powered"],ans:0,exp:""},
    {topic:"",q:"A differential relay in a twin generator system will cause",opts:["only one generator can supply a bus bar at a time","one generator always comes on line before the other","the generator voltages are nearly equal before they are paralleled Page 38 - Mod 13"],ans:2,exp:""},
    {topic:"",q:"Distilled or demineralised water would be added to an alkaline battery",opts:["in the aircraft","when the battery is fully charged","in the charging room only"],ans:2,exp:""},
    {topic:"",q:"When removing the load from a current transformer",opts:["short the terminals","place a resistor across each terminal","leave the terminals open"],ans:0,exp:""},
    {topic:"",q:"Wing steady light must be visible through",opts:["70 degrees","110 degrees","180 degrees"],ans:1,exp:""},
    {topic:"",q:"On AC ground power the interlock system is operated by pins",opts:["a and b","c and d","e and f"],ans:2,exp:""},
    {topic:"",q:"When paralleling two AC generators",opts:["it is important that they are in phase, and should be brought on in sequence ABC","it is important that they are in phase, and can be brought on in either ABC or CBA","they do not need to be in phase"],ans:0,exp:""},
    {topic:"",q:"The neutral shift sensor ensures that",opts:["after an auto trim, the elevator is moved to align with the stabiliser","after a mach trim, the stabiliser is moved to align with the elevator","after an auto trim, the stabiliser is moved to align with the elevator"],ans:0,exp:""},
    {topic:"",q:"Aileron to rudder crossfeed is applied in autopilot systems to",opts:["assist the aircraft back to datum after disturbance in yaw","prevents slip and skid in yaw","prevents aircraft yawing in the opposite direction to the turn"],ans:2,exp:""},
    {topic:"",q:"Stand off errors on localiser approach are washed out by",opts:["differentiating deviation signals","integrating deviation signals","integrating course error signals Page 39 - Mod 13"],ans:2,exp:""},
    {topic:"",q:"An open circuit in the temperature bulb as used in the DC ratiometer would cause",opts:["the pointer to read zero","the pointer to read mid scale","the pointer to read full scale"],ans:2,exp:""},
    {topic:"",q:"The instantaneous VSI is designed to",opts:["overcome the inherent lag by utilising an accelerometer","use an accelerometer to give a rate of climb/descent","improve the VSI output during acceleration greater than 1g"],ans:0,exp:""},
    {topic:"",q:"with a constant torque applied to a gyroscope, the rate of precession will",opts:["increase with a higher rotor speed","decrease with a higher rotor speed","decrease with a lower rotor speed"],ans:1,exp:""},
    {topic:"",q:"A gyroscope with a vertical spin axis has the roll torque motor located about the gyroscope's",opts:["lateral axis","longitudinal axis","vertical axis"],ans:1,exp:""},
    {topic:"",q:"The glideslope equipment operates in the",opts:["HF band","UHF band","VHF band"],ans:1,exp:""},
    {topic:"",q:"The loss of the vertical gyro signal to a flight director system would cause",opts:["aircraft to underbank","aircraft to overbank","aircraft to remain in level flight"],ans:2,exp:""},
    {topic:"",q:"In a flight director system the radio signal outputs from the navigation receiver are",opts:["DC","AC","pulsed DC"],ans:0,exp:""},
    {topic:"",q:"EICAS provides the following",opts:["engine parameters","engine parameters and system warnings","engine warnings and engine parameters Page 40 - Mod 13"],ans:1,exp:""},
    {topic:"",q:"The stabiliser is set to high setting when",opts:["the flaps are moving down","the flap are moving up","the flap are moving up or down"],ans:0,exp:""},
    {topic:"",q:"An auto land system displays Land 2 another failure will make the system",opts:["operational","passive","simplex"],ans:2,exp:""},
    {topic:"",q:"DSR TK (desired track) means",opts:["the bearing to capture the track","a great circle path on surface of earth connecting two way points","distance left or right from desired track"],ans:0,exp:""},
    {topic:"",q:"In helicopter Alt Hold uses a signal from",opts:["the barometric alt capsule","a rad alt output","a rad alt or capsule output depend on height"],ans:0,exp:""},
    {topic:"",q:"In a doppler VOR the 30Hz reference signal is",opts:["FM Modulated","AM Modulated","modulated with a 9960Hz"],ans:1,exp:""},
    {topic:"",q:"On aircraft an auto land during auto flare the auto throttle will",opts:["retard the throttle","reverse thrust","control throttle for a IAS"],ans:0,exp:""},
    {topic:"",q:"If an FM signal modulated by an audio signal the frequency of the audio would relate to the",opts:["amplitude","frequency","rate of frequency change"],ans:2,exp:""},
    {topic:"",q:"The normal axis on a helicopter is",opts:["straight down the rotor head","at 90 o to the C of G","at 90 o to the rotor head"],ans:0,exp:""},
    {topic:"",q:"On a HF radio set the clarifier control is used",opts:["to adjust the reinserted carrier due to instability in the RX","make the audio signal clearer","an Americanisum for volume Page 41 - Mod 13"],ans:0,exp:""},
    {topic:"",q:"A GPS aerial is polarised",opts:["vertically","horizontally","right hand circular"],ans:2,exp:""},
    {topic:"",q:"Mach trim threshold are set by the",opts:["pilot","engineer using aircraft maintenance manual","manufacture"],ans:2,exp:""},
    {topic:"",q:"An O ring in a wave guide is used to",opts:["correct the VSWR","stop arcing between the wave guide","stop moisture entering the wave guide"],ans:2,exp:""},
    {topic:"",q:"An RMI requires the following inputs:",opts:["Heading and radio deviation","Course and radio deviation","Radio deviation only"],ans:0,exp:""},
    {topic:"",q:"The versine signal is used in the",opts:["pitch channel only","roll channel only","pitch and roll channel"],ans:0,exp:""},
    {topic:"",q:"After a change in collective pitch the Rotor rpm will rise and fall. This is called",opts:["transient droop","static droop","under swing"],ans:0,exp:""},
    {topic:"",q:"Loran C Uses",opts:["16 KHz","20 Mhz","100 Khz"],ans:2,exp:""},
    {topic:"",q:"The amount of travel of a series actuator is",opts:["50% of control movement","10% of control movement","full control movement"],ans:0,exp:""},
    {topic:"",q:"After a change in pitch of a rotor blade the blade will be at maximum flap at",opts:["90 o","180 o","0 o"],ans:0,exp:""},
    {topic:"",q:"Emergency Electronic equipment is approved by",opts:["Aircraft Maintenance Manual","JAR (OPS) M","BCAR A4-8"],ans:1,exp:""},
    {topic:"",q:"The rotor disc is",opts:["the distance between tip to tip","the rotor head hub","the ground cushion"],ans:0,exp:""},
    {topic:"",q:"A DME is in auto stand by when",opts:["the ATC transponder is transmitting","the DME receives 200 - 300 pulses a second","the TCAS is transmitting"],ans:1,exp:""},
    {topic:"",q:"The aircraft is due north of a VOR station on a heading of 90 o What is a RMI display?",opts:["90 o","0 o","180 o"],ans:2,exp:""},
    {topic:"",q:"The flight director is on a localizer when the radio deviation signal is lost the aircraft would",opts:["continue on flying on the localizer","fly parallel to the localizer","drift of from the localizer on the same heading"],ans:1,exp:""},
    {topic:"",q:"Cat-2 autoland DH limits are",opts:["below 200 feet but not less than 100 ft","below 500 feet but not less than 400 ft.","below 300 feet and not less than 200 ft."],ans:0,exp:""},
    {topic:"",q:"Cat-1 autoland DH limits are",opts:["not less than 100 ft.","not less than 200 ft.","below 200 ft but not less than 100 ft."],ans:1,exp:""},
    {topic:"",q:"When GA is initiated?",opts:["Auto throttle disengages at 2000 ft/min rate and wings will level","Auto throttle remains engaged allowing pilot to control the throttles","Auto throttle remains engaged giving correct G/A thrust Page 43 - Mod 13"],ans:2,exp:""},
    {topic:"",q:"The controlling signal in pitch channel in the Flare mode are",opts:["integrated pitch and radio altitude.","G/S deviation and radio altitude.","integrated pitch and G/S deviation"],ans:0,exp:""},
    {topic:"",q:"During autoland failure of one channel is detected",opts:["all channels will disconnect in triplex system.","all channels will disconnect in dulpex system.","all channels will disconnect in dual-dual system."],ans:1,exp:""},
    {topic:"",q:"In triplex autoland system failure of one channel will",opts:["disconnect all channels","disconnect the failure channel and continue autoland approach","disconnect the failure channel and continue with a manual approach"],ans:1,exp:""},
    {topic:"",q:"During the flair mode the A/T throttle will",opts:["retard throttle to idle.","disconnect autothrottle","select reverse thrust."],ans:0,exp:""},
    {topic:"",q:"Roll out mode occurs",opts:["after flare","before flare","at alert height"],ans:0,exp:""},
    {topic:"",q:"Basic monitoring is function of",opts:["voting","signal comparison","signal summing"],ans:1,exp:""},
    {topic:"",q:"In series rudder system",opts:["the pilot cannot input to the system","the pilot can input to the system","yaw damping is only possible signal input Page 44 - Mod 13"],ans:1,exp:""},
    {topic:"",q:"in parallel rudder system,",opts:["the pilot can input on rudder pedals","The rudder pedals move in response to rudder movement","The rudder pedals are disconnected"],ans:1,exp:""},
    {topic:"",q:"The aileron/rudder signal is demodulated in the rudder channel amplifier. This means it is",opts:["AC","DC","DC output whose polarity is related to the phase of AC input"],ans:2,exp:""},
    {topic:"",q:"An increase in mach number will cause the",opts:["Cof P to move rearwards giving less downwash on the tail plane","Cof P to move rearwards giving more downwash on the tail plane","Cof P to move forwards giving less downwash on the tail plane"],ans:0,exp:""},
    {topic:"",q:"If one FMS fails in a duel system",opts:["system operation will not be affected","FMS CDU on fail side goes blank","FMS display transfers automatically from serviceable computer"],ans:2,exp:""},
    {topic:"",q:"To carry out FMS database update on FMS",opts:["use database loader","insert new EPROM","insert new data on CDU"],ans:0,exp:""},
    {topic:"",q:"To know the valid database on FMS",opts:["perform bite check","call up relevant page on CDU","call up relevant current status"],ans:1,exp:""},
    {topic:"",q:"Magnetic heading errors will be",opts:["positive if easterly","negative if easterly","negative if northerly"],ans:0,exp:""},
    {topic:"",q:"What will happen with a flux valve in a turn?",opts:["It will move once the aircraft is established on a new heading","Move as the aircraft moves","Stay fixed on magnetic north Page 45 - Mod 13"],ans:1,exp:""},
    {topic:"",q:"A helicopter autopilot uses",opts:["radio altitude for height hold and barometric altitude for altitude hold","barometric altitude for height hold and radio altitude for altitude hold","barometric altitude for both height and altitude hold"],ans:0,exp:""},
    {topic:"",q:"On an ILS approach what will cause the aircraft to fly onto the beam?",opts:["Height Deviation","Radio deviation","Course deviation"],ans:2,exp:""},
    {topic:"",q:"What of the following modes does a autopilot go through in correct sequence?",opts:["Flare, attitude, rollout","Attitude, flare, rollout","Rollout, attitude, flare"],ans:1,exp:""},
    {topic:"",q:"When can other autopilot modes can be select once Go-Around has been selected?",opts:["When aircraft has reached 5000ft","When reached a desired altitude","Disengage and reengage the AFCS system"],ans:1,exp:""},
    {topic:"",q:"If a helicopter rotor disc is rotating anticlockwise, view from above where would a pitch input be fed into the disc to",opts:["In front of the lateral axis","Right of the longitudinal axis","Left of the longitudinal axis"],ans:1,exp:""},
    {topic:"",q:"Forces on a helicopter in a power-on descent are",opts:["lift, drag thrust, weight","lift, drag, thrust","weight, drag, lift Page 46 - Mod 13"],ans:0,exp:""},
    {topic:"",q:"What is the primary purpose of a helicopter tail arm?",opts:["Provide a structure for mounting the stabiliser and anti torque rotor","Acts to help balance the centre of gravity of the helicopter","Provide directional control"],ans:0,exp:""},
    {topic:"",q:"How long is the time between the start of the P1 pulse and the P3 pulse ignoring the P2 pulse length?",opts:["21 micro seconds","8 micro seconds","17 micro seconds"],ans:0,exp:""},
    {topic:"",q:"What does the Radar contour button do?",opts:["Alter the beam shape","Alter the transmitter power","Alter the video amplifier"],ans:0,exp:""},
    {topic:"",q:"A radar response takes 329 micro seconds. How far away is the target?",opts:["12 miles","25 miles","40 miles"],ans:1,exp:""},
    {topic:"",q:"The VHF aerial resistance and transmission line resistance is",opts:["50 ohms","20 ohms","20 ohms and 50 ohms respectively"],ans:0,exp:""},
    {topic:"",q:"Alert Height is when",opts:["a decision of whether to land is made","an alert of the altitude of the aircraft is made","an alert of the position of the aircraft is made"],ans:1,exp:""},
    {topic:"",q:"Versine is used in which channel?",opts:["Pitch","Roll","Yaw"],ans:0,exp:""},
    {topic:"",q:"A Master Warning is issued when",opts:["overspeed & low cabin altitude occurs","cargo smoke & low oil quantity occurs","engine fire & generator trip occurs"],ans:0,exp:""},
    {topic:"",q:"Which is the most important part of preventative maintenance on HIRF installations?",opts:["Visual inspections","Insulation testing","CMC fault indications"],ans:0,exp:""},
    {topic:"",q:"When does the pressure in the standard atmosphere halve?",opts:["12,000ft","5,000ft","18,000ft"],ans:2,exp:""},
    {topic:"",q:"If an aircraft is entering a turn to the left, what input would the aileron to rudder crossfeed be?",opts:["Left Rudder","Right Rudder","No Rudder"],ans:0,exp:""},
    {topic:"",q:"If a control surface that is fitted with a balance tab is moved, what will happen to the tab?",opts:["It is moved manually in the opposite direction to the surface","It is moved automatically in the same direction as the surface","It is moved automatically in the opposite direction as the surface Page 48 - Mod 13"],ans:2,exp:""},
    {topic:"",q:"At which two points on a gas turbine engine is EPR measured?",opts:["Compressor inlet and jet pipe","Combustion chamber and jet pipe","Jet pipe and combustion chamber"],ans:0,exp:""},
    {topic:"",q:"If a stall is approaching, what indication does the pilot get?",opts:["Stick Shaker","Stick Nudger","EICAS warning"],ans:0,exp:""},
    {topic:"",q:"On a coupled approach what happens to the aircraft if it looses the localiser signal?",opts:["It will fly straight down the original course but will drift","It will fly in circles","It will fly on the heading the aircraft was on"],ans:0,exp:""},
    {topic:"",q:"If an autopilot is fed with radio deviation",opts:["it will stand off the centre line by a fixed amount","it will fly in circles","it will fly on the heading the aircraft was on"],ans:1,exp:""},
    {topic:"",q:"In what type of Doppler System do altitude holes appear?",opts:["FM","Pulse","FM and Pulse"],ans:0,exp:""},
    {topic:"",q:"If an aircraft moves in yaw what axis is it moving about?",opts:["Normal","Longitudinal","Lateral Page 49 - Mod 13"],ans:0,exp:""},
    {topic:"",q:"The neutral shift system augments control of the",opts:["stabiliser","elevator","spoilers"],ans:1,exp:""},
    {topic:"",q:"On a full time Fly-by-wire system a nose up command causes",opts:["the two elevator surfaces on each side of the stabiliser to move up","all the elevators on each wing to move up","the two Ailerons on each wing to move up"],ans:0,exp:""},
    {topic:"",q:"What are ground spoilers used for?",opts:["To dump lift","To assist the aircraft coming to a stop","To slow the aircraft"],ans:0,exp:""},
    {topic:"",q:"If the aircraft is to be rolled to the right where does the pilot feed in this command?",opts:["Control Wheel","Control Column","Rudder Pedals"],ans:0,exp:""},
    {topic:"",q:"What is the typical aircraft hydraulic system pressure?",opts:["3000 psi","1000 psi","300 psi"],ans:0,exp:""},
    {topic:"",q:"If a bonding lead is found to be broken and a spare is unavailable you must",opts:["replace with a self manufactured cable of the same type but larger","defer the defect until correct spares are available","splice the broken lead"],ans:0,exp:""},
    {topic:"",q:"What is the bonding value between secondary structure?",opts:["0.5","1 ohm","Between 1Megohm and 500,000"],ans:1,exp:""},
    {topic:"",q:"What is the diagonal part of the landing gear called?",opts:["Drag Strut","Drag Wire","Shock Absorber Page 50 - Mod 13"],ans:0,exp:""},
    {topic:"",q:"What is the advancing blade on a helicopter doing?",opts:["Increasing in lift","Going to the highest point","Increasing in drag"],ans:0,exp:""},
    {topic:"",q:"In a series actuator fitted to a helicopter how much authority does it have?",opts:["10% approximately","100%","50%"],ans:0,exp:""},
    {topic:"",q:"What is the output of a localiser NAV receiver?",opts:["Polarity sensitive AC","Polarity sensitive DC","Either"],ans:1,exp:""},
    {topic:"",q:"What does an INS calculate on power up?",opts:["Last Known Longitude","Last Known Latitude","Last Known Longitude & Latitude"],ans:1,exp:""},
    {topic:"",q:"If a series actuator is fitted in the cyclic control circuit of a helicopter what effect will an autopilot input have?",opts:["The cyclic lever will move in proportion to the autopilot input","The cyclic lever will not move","The flight director bars only will move"],ans:1,exp:""},
    {topic:"",q:"On an aircraft fitted with a CMC how do you get to the system pages?",opts:["Through the ground test function","Through the Existing faults function","Through the Present Leg faults function"],ans:0,exp:""},
    {topic:"",q:"What is the purpose of the autopilot trim indication?",opts:["The voltage activity in the servo amp","Trim tab position","Control surface position"],ans:0,exp:""},
    {topic:"",q:"What is the entry angle of an MLS installation +/-?",opts:["62","42","20"],ans:1,exp:""},
    {topic:"",q:"When using a bonding tester you",opts:["use the 6ft lead for testing different points","use the 60ft lead for testing different points","use either leads for the testing Page 51 - Mod 13"],ans:0,exp:""},
    {topic:"",q:"What is the swash plate on a helicopter used for?",opts:["Control of the pitch of the rotor blades","Control of the speed of the rotor blades","Control of the flap of the rotor blades"],ans:0,exp:""},
    {topic:"",q:"What does a piezo electric type vibration sensor detect?",opts:["Disturbances","Velocity","Pressure changes"],ans:2,exp:""},
    {topic:"",q:"What should be carried out prior to working on or near control surfaces?",opts:["Ensure Hydraulics are selected off","Pull & tag circuit breakers","Wear ear protection"],ans:0,exp:""},
    {topic:"",q:"Instantaneous Vertical Speed Indicator has instant values of Vertical Speed by",opts:["blocking off static and by using an accelerometer","using a plunger to correct any lagging of the indicator","blocking off pitot pressure and by using an accelerometer"],ans:0,exp:""},
    {topic:"",q:"What is the glide slope frequency range?",opts:["108 - 112 Mhz","108 - 112 Ghz","329 - 335 Mhz"],ans:2,exp:""},
    {topic:"",q:"What would indicate the state of charge of a lead acid battery?",opts:["Fluctuations in the level of the electrolyte","Fluctuations in the SG of the electrolyte","Fluctuations in the terminal voltage"],ans:1,exp:""},
    {topic:"",q:"What is the aural warning of an aircraft overspeed?",opts:["Bell sound","Clacking sound","Horn sound Page 52 - Mod 13"],ans:1,exp:""},
    {topic:"",q:"What is a slot used for?",opts:["To reinforce the boundary layer","Increased angle of attack during approach","Increase the speed of the airflow"],ans:0,exp:""},
    {topic:"",q:"A Boost Gauge reads",opts:["above or below ambient atmospheric pressure","absolute pressure","above or below ISA atmospheric pressure"],ans:1,exp:""},
    {topic:"",q:"Angle of Attack is the angle between cord line and",opts:["relative air flow","tip path plane","horizontal axis"],ans:0,exp:""},
    {topic:"",q:"What is the Speed of an ARINC 429 system",opts:["2.3 - 23 Mhz","2 - 6 GHz","100 KHz"],ans:2,exp:""},
    {topic:"",q:"A high lift device is used for",opts:["take off and landing","take off only","landing only"],ans:0,exp:""},
    {topic:"",q:"What is jitter used for in a DME transmission?",opts:["To make an installation recognise it's own transmission","To make sure only strong signals are replied to in a dense area","To make an aircraft recognise a DME in a quiet area"],ans:0,exp:""},
    {topic:"",q:"The difference between transient droop and static droop is",opts:["underswing","overswing","a hole in one"],ans:0,exp:""},
    {topic:"",q:"With a helicopter with a twin blade same gimbal it is",opts:["semi rigid","rigid","fully articulating"],ans:0,exp:""},
    {topic:"",q:"What is lapse rate?",opts:["Pressure changes with altitude","Temperature changes with altitude","Density changes with altitude"],ans:1,exp:""},
    {topic:"",q:"In a boost gauge system the sensing element contains",opts:["1 capsule","2 capsules","3 capsules"],ans:1,exp:""},
    {topic:"",q:"If an aircraft moves in roll it is moving about the",opts:["normal axis","lateral axis","longitudinal axis"],ans:2,exp:""},
    {topic:"",q:"LOC signal modulation is",opts:["50 %","20 %","10 % Page 57 - Mod 13"],ans:1,exp:""},
    {topic:"",q:"If increasing altitude at constant IAS, TAS will",opts:["decrease","increase","remain the same"],ans:1,exp:""},
    {topic:"",q:"How does a delta wing aircraft move about the pitch and roll axis?",opts:["Elevator s","Elevons","Ailerons"],ans:1,exp:""},
    {topic:"",q:"If a roll was commenced, what command would the versine generator give?",opts:["Up Elevator","Left rudder","Down elevator"],ans:0,exp:""},
    {topic:"",q:"What effect does lowering the flaps for takeoff have?",opts:["Increases lift & reduces drag","Increases lift and drag","Increase lift only"],ans:1,exp:""},
    {topic:"",q:"What effect does lowering flaps for takeoff have?",opts:["Reduces takeoff and landing speeds","Reduces takeoff speeds only","Reduces landing speeds only"],ans:0,exp:""},
    {topic:"",q:"What does a vibration type sensor measure?",opts:["Maximum deflection","Frequency of deflections","Direction of flexing"],ans:1,exp:""},
    {topic:"",q:"The result of the equation (Dev E - Dev W)/2 is known as",opts:["Coefficient B","Coefficient A","Coefficient C"],ans:0,exp:""},
    {topic:"",q:"ADF operates within which frequencies?",opts:["200 KHz - 1000 KHz","118 MHz - 132 MHz","32 KHz - 64 KHz"],ans:0,exp:""},
    {topic:"",q:"Cat IIIB landing, up to what phase is LOC signal used?",opts:["Roll out","Flare","Touchdown"],ans:1,exp:""},
    {topic:"",q:"FMC mode that can be selected through the CDU is",opts:["DME Freq","LNAV","CRZ Page 59 - Mod 13"],ans:2,exp:""},
    {topic:"",q:"Which would you use to test an aircraft transponder altitude reporting system?",opts:["Read the altitude directly from ATC-600 panel","Transfer the code displayed by the ATC- 600 into binary","Check the altitude code with the correct alt/code table"],ans:0,exp:""},
    {topic:"",q:"If the localiser signal is only applied to the A/P roll channel",opts:["aircraft flies parallel to the runway centre line","aircraft flies along the runway centre line","aircraft flies in circles"],ans:2,exp:""},
    {topic:"",q:"WX radar display the time base is",opts:["saw tooth wave form","trapezoidal wave form","rectangular wave form Page 60 - Mod 13"],ans:0,exp:""},
    {topic:"",q:"A helicopter needs to re-trim",opts:["indication is shown on the API","indication is shown on the command bars of the EHSI","indication is shown on the command bars of the attitude indicator"],ans:0,exp:""},
    {topic:"",q:"Anti cross-talk network for unwanted signals uses",opts:["attenuation first then amplification","amplification first then attenuation","no attenuation but amplification"],ans:0,exp:""},
    {topic:"",q:"at take off, if the flaps are lowered there is a",opts:["large increase in lift and drag","small increase in lift and drag","large increase in lift and small increase in drag"],ans:0,exp:""},
    {topic:"",q:"With no.1 h.f. system transmitting the interlock circuit",opts:["allows no.2 h.f. to receive only","allows no.2 h.f. to transmit and receive","does not allow no.2 to transmit or receive Page 62 - Mod 13"],ans:2,exp:""},
    {topic:"",q:"Aircraft is north of VOR beacon, course is set to 90 degrees, RMI indicates",opts:["90","180","0"],ans:1,exp:""},
    {topic:"",q:"in an auto trim horizontal stabiliser, 'low' speed mode is when",opts:["flaps are retracted","landing gear up and locked","flaps extended"],ans:0,exp:""},
    {topic:"",q:"An aircraft receives a response from a DME station, 1236 microseconds after transmitting the interrogation. What is the slant range to the station?",opts:["96 nautical miles","100 nautical miles","104 nautical miles"],ans:0,exp:""},
    {topic:"",q:"If the VOR track error is 2 dots, how many degrees off track is the aircraft?",opts:["10","5","2.5"],ans:0,exp:""},
    {topic:"",q:"What frequency range does ACARS operate in?",opts:["2-30 MHz","118-136 MHz","4-5 GHz"],ans:1,exp:""},
    {topic:"",q:"An FM signal would have it's sideband signals",opts:["above the carrier signal","below the carrier signal","No sidebands present"],ans:2,exp:""},
    {topic:"",q:"A Doppler VOR station's transmissions",opts:["can be received and processed with a conventional VOR receiver","can not be received and processed with a conventional VOR receiver","can be received but not processed with a conventional VOR receiver"],ans:0,exp:""},
    {topic:"",q:"Wing can spoilers be used?",opts:["To assist the respective down going aileron in a turn","As ground spoilers on landing","To assist the elevators"],ans:2,exp:""},
    {topic:"",q:"Dutch Roll affects",opts:["pitch and roll simultaneously","pitch and yaw simultaneously","yaw and roll simultaneously"],ans:2,exp:""},
    {topic:"",q:"When more than one D.R. compass is fitted on an aircraft or where a D.R. compass serves as a standby to a remote reading compass",opts:["only the master compass readings and adjustments carried out and remaining compasses are adjusted with master compass","all readings and adjustments for each compass should be made simultaneously on each heading","all readings and adjustments for each compass should be made at any one heading only"],ans:1,exp:""},
    {topic:"",q:"Compass error remaining after all the corrections, which is used for entry on the deviation card should not exceed",opts:["2 degrees","3 degrees","5 degrees"],ans:1,exp:""},
    {topic:"",q:"Compass error remaining after all corrections are made is called",opts:["apparent error","residual error","index error"],ans:1,exp:""},
    {topic:"",q:"Instruments used on an aircraft are in some instances fitted with cover glasses whose surfaces are bloomed to reduce",opts:["Parallax error","Surface reflection","Static to avoid dust attraction"],ans:1,exp:""},
    {topic:"",q:"Versine signal is governed by",opts:["roll","pitch","yaw"],ans:1,exp:""},
    {topic:"",q:"Stick shaker activates at a speed which is above the stalling speed by",opts:["4%","7%","10.321%"],ans:1,exp:""},
    {topic:"",q:"A D.R. compass fitted on an aircraft. The safe distance for electrical cables carrying electrical current is",opts:["20 inches","24 inches","28 inches"],ans:1,exp:""},
    {topic:"",q:"Oscillation and hunting of flight control surface are prevented by",opts:["Tachogenerator","Feedback from control surface","Feedback from servo motor"],ans:0,exp:""},
    {topic:"",q:"Radar beamwidth improves",opts:["range resolution","range accuracy","bearing resolution"],ans:2,exp:""},
    {topic:"",q:"A transformer has a power input of 115V AC. What is the output voltage?",opts:["115V","345V","460V"],ans:2,exp:""},
    {topic:"",q:"on a VSI fitted on an aircraft, for climb and descent indication",opts:["a set screw is provided for zero adjustment","it does not have any adjustment","a set screw is provided for climb/descent increments"],ans:0,exp:""},
    {topic:"",q:"When more than one D.R.Compass is fitted on an aircraft or where a D.R.compass serves as a standby to a remote reading compass",opts:["Only the master compass reading and adjustment carried out and remaining compasses are adjusted with master compass.","All reading and adjustments fo reach compass should be made simultaneously on each heading.","All reading and adjustment for each compass should be made at any one heading only."],ans:1,exp:""},
    {topic:"",q:"Compass error remaining after all the corrections, which is used for entry on the deviation card should not exceed",opts:["2 Degree","3 Degree","5 Degree"],ans:1,exp:""},
    {topic:"",q:"Compass error remaining after all corrections are made is called",opts:["apparent error","residual error","index error"],ans:1,exp:""},
    {topic:"",q:"Instruments used on an aircraft are in some instances fitted with cover glasses whose surfaces are bloomed to reduce",opts:["parallax error.","surface reflection.","static to avoid dust attraction."],ans:1,exp:""},
    {topic:"",q:"Versine signal is governed by",opts:["roll","pitch","yaw Page 67 - Mod 13"],ans:1,exp:""},
    {topic:"",q:"Increasing the real load primarily",opts:["decreases frequency","decreases output voltage","increases output voltage and increases frequency"],ans:2,exp:""},
    {topic:"",q:"Inductive reactive load causes",opts:["no effect on torque but produces extra heat dissipated","increase in torque and increase in heat dissipated","increase in torque only"],ans:2,exp:""},
    {topic:"",q:"The power factor of an AC generator identifies the proportion of",opts:["apparent power from the generator that does work","reactive power from the generator that does work","real power from the generator that does work"],ans:2,exp:""},
    {topic:"",q:"The control of hydraulically powered emergency electrical generator frequency is by",opts:["angle of swash plate","IDG","restriction valve"],ans:0,exp:""},
    {topic:"",q:"Differential protection in an AC system protects against",opts:["A reverse current flowing from the battery","short circuits","line-line, line-line-line, line-earth faults"],ans:2,exp:""},
    {topic:"",q:"When resetting the CSD on the ground, the engine should be",opts:["stationary","rotating at idle","rotating at Nsync"],ans:0,exp:""},
    {topic:"",q:"One of the main purposes of a CSD is to",opts:["enable generators to be paralleled","prevent engine overload","maintain constant load on the generator"],ans:0,exp:""},
    {topic:"",q:"in a undervolt condition in an AC generator system, the most likely consequence is",opts:["activation of the time delay circuit","de-activation of the field regulatory TRs","energise the bus tie relay"],ans:0,exp:""},
    {topic:"",q:"If voltage and frequency of the generator drop to zero in flight, it would be an indication that the",opts:["CSD drives shaft had sheared","phase sequence detection circuit has operated","bus tie interlock is inoperative Page 68 - Mod 13"],ans:0,exp:""},
    {topic:"",q:"Assuming all systems are operating normally, as aircraft electrical load increases, generator output voltage will",opts:["decrease and amperage output increases","increases and amperage output increases","remain constant and amperage output increases"],ans:2,exp:""},
    {topic:"",q:"Battery trays are",opts:["metal for earthing purposes","metal with PVC coating and anti corrosive paint","absorbent to soak up electrolyte"],ans:1,exp:""},
    {topic:"",q:"When installing multiple batteries on aircraft they are connected in",opts:["parallel","series","either parallel or series and switched between as an option"],ans:2,exp:""},
    {topic:"",q:"What is the small pin on the DC ground power connector?",opts:["Ground or earth","Positive to battery relay","Positive to external power relay"],ans:2,exp:""},
    {topic:"",q:"Maximum battery temperature on charging before protection circuit starts is",opts:["71 degrees F","144 Degrees F","144 Degrees C"],ans:1,exp:""},
    {topic:"",q:"If an aircraft has no battery charger the battery is charged by",opts:["constant voltage","constant current","constant current until a predetermined limit when it automatically switches to constant voltage"],ans:0,exp:""},
    {topic:"",q:"Battery charging procedures can be found in ATA",opts:["Chapter 24 Section 21","Chapter 24 Section 31","Chapter 31 Section 21"],ans:1,exp:""},
    {topic:"",q:"In a carbon pile regulator the resistive element is",opts:["in series with the field and changes resistance with changing length","in series with the field and changes resistance with surface area contact","in parallel with the field and changes resistance with changing length Page 69 - Mod 13"],ans:1,exp:""},
    {topic:"",q:"The output of a carbon pile regulator with no variation of loading is",opts:["stationary","fluctuating","pulse width modulating"],ans:0,exp:""},
    {topic:"",q:"In a transistor voltage regulator the voltage output is controlled by",opts:["transformers and transistors","diodes and transformers","zeners and transistors"],ans:2,exp:""}
  ]
};